· Creating environments
· Discovering benchmarks
·· Uninstalling from conda-py3.8-cython-joblib-numpy-scipy-threadpoolctl
·· Building 7e197fd6 <main> for conda-py3.8-cython-joblib-numpy-scipy-threadpoolctl
·· Installing 7e197fd6 <main> into conda-py3.8-cython-joblib-numpy-scipy-threadpoolctl
· Running 6 total benchmarks (1 commits * 1 environments * 6 benchmarks)
[  0.00%] · For scikit-learn commit 7e197fd6 <main>:
[  0.00%] ·· Benchmarking conda-py3.8-cython-joblib-numpy-scipy-threadpoolctl
[ 16.67%] ··· Setting up ensemble:96                                          ok
[ 16.67%] ··· ...dientBoostingClassifierBenchmark.peakmem_fit              99.3M
[ 33.33%] ··· ...tBoostingClassifierBenchmark.peakmem_predict              87.6M
[ 50.00%] ··· ...GradientBoostingClassifierBenchmark.time_fit          2.95±0.2s
[ 66.67%] ··· ...ientBoostingClassifierBenchmark.time_predict           101±10ms
[ 83.33%] ··· ...BoostingClassifierBenchmark.track_test_score 0.7230709112942986
[100.00%] ··· ...oostingClassifierBenchmark.track_train_score 0.9812160155622751
[ 11.11%] · Loading machine info
[ 22.22%] · Getting params, commits, tags and branches
[ 22.22%] ·· Error running /usr/bin/git rev-list --first-parent master (exit status 128)
             STDOUT -------->
             
             STDERR -------->
             fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
             Use '--' to separate paths from revisions, like this:
             'git <command> [<revision>...] -- [<file>...]'

Traceback (most recent call last):
  File "/home/ubuntu/miniconda/envs/skl_benchmark/bin/asv", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/miniconda/envs/skl_benchmark/lib/python3.8/site-packages/asv/main.py", line 38, in main
    result = args.func(args)
  File "/home/ubuntu/miniconda/envs/skl_benchmark/lib/python3.8/site-packages/asv/commands/__init__.py", line 49, in run_from_args
    return cls.run_from_conf_args(conf, args)
  File "/home/ubuntu/miniconda/envs/skl_benchmark/lib/python3.8/site-packages/asv/commands/publish.py", line 80, in run_from_conf_args
    return cls.run(conf=conf, range_spec=args.range, pull=not args.no_pull)
  File "/home/ubuntu/miniconda/envs/skl_benchmark/lib/python3.8/site-packages/asv/commands/publish.py", line 171, in run
    branches = dict(
  File "/home/ubuntu/miniconda/envs/skl_benchmark/lib/python3.8/site-packages/asv/commands/publish.py", line 172, in <genexpr>
    (branch, repo.get_branch_commits(branch))
  File "/home/ubuntu/miniconda/envs/skl_benchmark/lib/python3.8/site-packages/asv/plugins/git.py", line 177, in get_branch_commits
    return self.get_hashes_from_range(self.get_branch_name(branch))
  File "/home/ubuntu/miniconda/envs/skl_benchmark/lib/python3.8/site-packages/asv/plugins/git.py", line 125, in get_hashes_from_range
    output = self._run_git(args, valid_return_codes=(0, 1), dots=False)
  File "/home/ubuntu/miniconda/envs/skl_benchmark/lib/python3.8/site-packages/asv/plugins/git.py", line 74, in _run_git
    return util.check_output([self._git] + args, env=env, **kwargs)
  File "/home/ubuntu/miniconda/envs/skl_benchmark/lib/python3.8/site-packages/asv/util.py", line 754, in check_output
    raise ProcessError(args, retcode, stdout, stderr)
asv.util.ProcessError: Command '/usr/bin/git rev-list --first-parent master' returned non-zero exit status 128
