***** Runner *****

· Creating environments
· Discovering benchmarks
·· Uninstalling from conda-py3.11-cython3.0.3-joblib1.3.2-numpy1.25.2-pandas2.1.0-scipy1.11.2-threadpoolctl3.2.0
·· Building b8229daa <main> for conda-py3.11-cython3.0.3-joblib1.3.2-numpy1.25.2-pandas2.1.0-scipy1.11.2-threadpoolctl3.2.0
·· Error running /home/ubuntu/scikit-learn/asv_benchmarks/env/f6ff9b5b333fe13b488feffb65c69a2e/bin/python -mpip wheel --no-deps --no-index -w /home/ubuntu/scikit-learn/asv_benchmarks/env/f6ff9b5b333fe13b488feffb65c69a2e/asv-build-cache/b8229daafee0e50690d4b8447f93cf1069ba6880 /home/ubuntu/scikit-learn/asv_benchmarks/env/f6ff9b5b333fe13b488feffb65c69a2e/project (exit status 1)
   STDOUT -------->
   Processing /home/ubuntu/scikit-learn/asv_benchmarks/env/f6ff9b5b333fe13b488feffb65c69a2e/project
     Preparing metadata (pyproject.toml): started
     Preparing metadata (pyproject.toml): finished with status 'error'
   STDERR -------->
     error: subprocess-exited-with-error
   
     × Preparing metadata (pyproject.toml) did not run successfully.
     │ exit code: 1
     ╰─> [53 lines of output]
         Partial import of sklearn during the build process.
         Traceback (most recent call last):
           File "/home/ubuntu/scikit-learn/asv_benchmarks/env/f6ff9b5b333fe13b488feffb65c69a2e/lib/python3.11/site-packages/setuptools/_distutils/spawn.py", line 57, in spawn
             proc = subprocess.Popen(cmd, env=env)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           File "/home/ubuntu/scikit-learn/asv_benchmarks/env/f6ff9b5b333fe13b488feffb65c69a2e/lib/python3.11/subprocess.py", line 1026, in __init__
             self._execute_child(args, executable, preexec_fn, close_fds,
           File "/home/ubuntu/scikit-learn/asv_benchmarks/env/f6ff9b5b333fe13b488feffb65c69a2e/lib/python3.11/subprocess.py", line 1950, in _execute_child
             raise child_exception_type(errno_num, err_msg, err_filename)
         FileNotFoundError: [Errno 2] No such file or directory: 'gcc'
   
         The above exception was the direct cause of the following exception:
   
         Traceback (most recent call last):
           File "/home/ubuntu/scikit-learn/asv_benchmarks/env/f6ff9b5b333fe13b488feffb65c69a2e/lib/python3.11/site-packages/setuptools/_distutils/unixccompiler.py", line 185, in _compile
             self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
           File "/home/ubuntu/scikit-learn/asv_benchmarks/env/f6ff9b5b333fe13b488feffb65c69a2e/lib/python3.11/site-packages/setuptools/_distutils/ccompiler.py", line 1041, in spawn
             spawn(cmd, dry_run=self.dry_run, **kwargs)
           File "/home/ubuntu/scikit-learn/asv_benchmarks/env/f6ff9b5b333fe13b488feffb65c69a2e/lib/python3.11/site-packages/setuptools/_distutils/spawn.py", line 63, in spawn
             raise DistutilsExecError(
         distutils.errors.DistutilsExecError: command 'gcc' failed: No such file or directory
   
         During handling of the above exception, another exception occurred:
   
         Traceback (most recent call last):
           File "/home/ubuntu/scikit-learn/asv_benchmarks/env/f6ff9b5b333fe13b488feffb65c69a2e/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
             main()
           File "/home/ubuntu/scikit-learn/asv_benchmarks/env/f6ff9b5b333fe13b488feffb65c69a2e/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
             json_out['return_val'] = hook(**hook_input['kwargs'])
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           File "/home/ubuntu/scikit-learn/asv_benchmarks/env/f6ff9b5b333fe13b488feffb65c69a2e/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
             return hook(metadata_directory, config_settings)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           File "/home/ubuntu/scikit-learn/asv_benchmarks/env/f6ff9b5b333fe13b488feffb65c69a2e/lib/python3.11/site-packages/setuptools/build_meta.py", line 396, in prepare_metadata_for_build_wheel
             self.run_setup()
           File "/home/ubuntu/scikit-learn/asv_benchmarks/env/f6ff9b5b333fe13b488feffb65c69a2e/lib/python3.11/site-packages/setuptools/build_meta.py", line 507, in run_setup
             super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
           File "/home/ubuntu/scikit-learn/asv_benchmarks/env/f6ff9b5b333fe13b488feffb65c69a2e/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
             exec(code, locals())
           File "<string>", line 640, in <module>
           File "<string>", line 634, in setup_package
           File "<string>", line 565, in configure_extension_modules
           File "/home/ubuntu/scikit-learn/asv_benchmarks/env/f6ff9b5b333fe13b488feffb65c69a2e/project/sklearn/_build_utils/__init__.py", line 46, in cythonize_extensions
             basic_check_build()
           File "/home/ubuntu/scikit-learn/asv_benchmarks/env/f6ff9b5b333fe13b488feffb65c69a2e/project/sklearn/_build_utils/pre_build_helpers.py", line 73, in basic_check_build
             compile_test_program(code)
           File "/home/ubuntu/scikit-learn/asv_benchmarks/env/f6ff9b5b333fe13b488feffb65c69a2e/project/sklearn/_build_utils/pre_build_helpers.py", line 31, in compile_test_program
             ccompiler.compile(
           File "/home/ubuntu/scikit-learn/asv_benchmarks/env/f6ff9b5b333fe13b488feffb65c69a2e/lib/python3.11/site-packages/setuptools/_distutils/ccompiler.py", line 600, in compile
             self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
           File "/home/ubuntu/scikit-learn/asv_benchmarks/env/f6ff9b5b333fe13b488feffb65c69a2e/lib/python3.11/site-packages/setuptools/_distutils/unixccompiler.py", line 187, in _compile
             raise CompileError(msg)
         distutils.errors.CompileError: command 'gcc' failed: No such file or directory
         [end of output]
   
     note: This error originates from a subprocess, and is likely not a problem with pip.
   error: metadata-generation-failed
   
   × Encountered error while generating package metadata.
   ╰─> See above for output.
   
   note: This is an issue with the package mentioned above, not pip.
   hint: See above for details.

·· Failed to build the project and import the benchmark suite.


***** Publish *****

[11.11%] · Loading machine info
[22.22%] · Getting params, commits, tags and branches
[33.33%] · Loading results
[44.44%] · Detecting steps
[55.56%] · Generating graphs
[66.67%] · Generating output for SummaryGrid
[77.78%] · Generating output for SummaryList
[88.89%] · Generating output for Regressions
[100.00%] · Writing index


***** Dependencies *****

# packages in environment at /home/ubuntu/scikit-learn/asv_benchmarks/env/f6ff9b5b333fe13b488feffb65c69a2e:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
asv-runner                0.1.0                    pypi_0    pypi
bzip2                     1.0.8                hd590300_5    conda-forge
ca-certificates           2023.11.17           hbcca054_0    conda-forge
cython                    3.0.3           py311hb755f60_0    conda-forge
joblib                    1.3.2              pyhd8ed1ab_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libblas                   3.9.0           20_linux64_openblas    conda-forge
libcblas                  3.9.0           20_linux64_openblas    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_3    conda-forge
libgfortran-ng            13.2.0               h69a702a_3    conda-forge
libgfortran5              13.2.0               ha4646dd_3    conda-forge
libgomp                   13.2.0               h807b86a_3    conda-forge
liblapack                 3.9.0           20_linux64_openblas    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.25          pthreads_h413a1c8_0    conda-forge
libsqlite                 3.44.2               h2797004_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_3    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
ncurses                   6.4                  h59595ed_2    conda-forge
numpy                     1.25.2          py311h64a7726_0    conda-forge
openssl                   3.2.0                hd590300_1    conda-forge
pandas                    2.1.0           py311h320fe9a_0    conda-forge
pip                       23.3.1             pyhd8ed1ab_0    conda-forge
pympler                   1.0.1                    pypi_0    pypi
python                    3.11.6          hab00c5b_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
python_abi                3.11                    4_cp311    conda-forge
pytz                      2023.3.post1       pyhd8ed1ab_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
scipy                     1.11.2          py311h64a7726_1    conda-forge
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
threadpoolctl             3.2.0              pyha21a80b_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge


***** Threadpool info *****

[]


***** System info *****

Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          8
On-line CPU(s) list:             0-7
Vendor ID:                       GenuineIntel
Model name:                      Intel Core Processor (Haswell, no TSX)
CPU family:                      6
Model:                           60
Thread(s) per core:              1
Core(s) per socket:              1
Socket(s):                       8
Stepping:                        1
BogoMIPS:                        4589.37
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single pti fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       256 KiB (8 instances)
L1i cache:                       256 KiB (8 instances)
L2 cache:                        32 MiB (8 instances)
L3 cache:                        128 MiB (8 instances)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Unknown: No mitigations
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Unknown: Dependent on hypervisor status
Vulnerability Tsx async abort:   Not affected
MemTotal:       16384564 kB
